events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        listen [::]:80;

        location = /robots.txt {
            root /app;
            default_type text/plain;
            add_header Access-Control-Allow-Origin * always;
        }

        location ^~ /.well-known/ {
            root /app;
            default_type "application/octet-stream";
            add_header Access-Control-Allow-Origin * always;
        }

        location /files {
            root /app/public;
            default_type "application/octet-stream";
        }

        location / {
            root /app/public;
            default_type "text/html";
            index index.html;
            try_files  $uri $uri.html $uri/index.html;
        }
    }
}
